name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy on Yandex.Cloud
    runs-on: ubuntu-latest

    env: 
      registry: cr.yandex/crp50j9hporsn9435fmm
      app_name: yandextoday

    steps:
      - uses: actions/checkout@v2

      - name: Pull project to Yandex.Cloud
        run: | 
          echo '${{ secrets.IAM }}' | docker login --username oauth --password-stdin cr.yandex
          docker build . -t ${{ env.registry }}/yandext:${{ env.app_name }}
          docker push ${{ env.registry }}/yandext:${{ env.app_name }}
      - name: Deploy project to Yandex.Cloud
        run: |
          yc serverless function invoke --id "d4eht2ijlv23pvt5pacv"
